// Generated by IB v0.7.2 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import "Stubs.h"

@implementation AppDelegate
@end

@implementation NSString
@end

@implementation UIAlertController
@end

@implementation UIColor
@end

@implementation UIView
@end

@implementation AboutAppController
@end

@implementation ConfigController
@end

@implementation AppInformationController
@end

@implementation BookmarkCommentController
@end

@implementation HatebuConfigController
@end

@implementation PocketConfigController
@end

@implementation PocketItemViewController
@end

@implementation PocketItemsController
@end

@implementation PocketWebViewController
@end

@implementation SettingsController
@end

@implementation UrlActionController
@end

@implementation Bookmark
@end

@implementation PocketItem
@end

@implementation Setting
@end

@implementation BookmarkCommentCell
@end

@implementation PocketItemCell
@end

@implementation PocketItemView
@end

